### ISSUE TITLE
@react-native-community/eslint-config releases

### ISSUE THREAD

**Issue by ceyhun** [react-native-community/releases#138]
What is the release process for `@react-native-community/eslint-config`?

I'm also not sure if this is the correct place to ask because `eslint-config-react-native-community` is under `https://github.com/facebook/react-native/`'s `packages` folder but the npm package is named `@react-native-community/eslint-config`.

**Comment by kelset** [comment]
Hello there 👋
This is not the right repository to open this kind of issue, so I'll close it. But, to answer your questions:

>  What is the release process for @react-native-community/eslint-config?

A new version is released whenever there are changes in the configurations. Is there any specific reason why you are asking?

> eslint-config-react-native-community is under https://github.com/facebook/react-native/'s packages folder but the npm package is named @react-native-community/eslint-config

Yeah, I can see why you may be confused, but it's just a name ;) the reason why it lives in the RN repo is that it's an export from the FB config but we decided to give it a unique name under the community scope since it's the one we want to use everywhere in the org.

**Comment by ceyhun** [comment]
Thanks you for answering my question anyways. The correct repo for this issue is then [facebook/react-native](https://github.com/facebook/react-native)?

> A new version is released whenever there are changes in the configurations. Is there any specific reason why you are asking?

The latest version over npm is [0.0.5](https://www.npmjs.com/package/@react-native-community/eslint-config) and is 4 months old. There has been a couple of changes in the configurations but a new version is not yet released.

**Comment by kelset** [comment]
> The correct repo for this issue
is the issue what you say afterwards

> There has been a couple of changes in the configurations but a new version is not yet released.

Because then it's not an issue per se - if I understand you'd want to ask for a new release, not report an actual issue or a bug? 🤔

**Comment by ceyhun** [comment]
Correct 👍 I would like to ask for a new release but I don't know how and where?

**Comment by kelset** [comment]
I don't want to sound harsh but you ""should not"" *ask* for a release, IMHO 😅

If it wasn't done already there is probably some reason, and by asking you are sort of putting pressure on the people responsible for it (which, I have to admit, I am not sure I know who is) - and overall it's just a eslint-config so you can always modify your local .eslintrc file. That said I'll try to understand better the release process for it and who is involved so that I can rely them your concern.

**Comment by ceyhun** [comment]
Thanks a lot 🎉 I would also be happy to help with releases if that could relieve the pressure a bit. I just didn't know where to start 😅
