### ISSUE TITLE
Changelog maintenance

### ISSUE THREAD

**Issue by kelset** [react-native-community/releases#47]
I don't know if this discussion is right place, but there is no space where users and developers can read changelogs about patch versions of RN in friendly way.
Every minor (major because before version 1?) version of RN has nice description about what has changed but patch versions doesn't. I think there is legitimate requirement to tell what is different in every version. Many changes are significant (eg. Android studio 3.2/Xcode 10 support, some important fixes).
It could increase awareness about RN and making better apps because upgrading between last patch version and new minor version is less annoying (baby steps, less painful changes in code).
On the other hand it could also decrease opening some unnecessary issues on RN Github project cause every change is visible in human readable form.

Is there any way how to automatically generate changelog from release notes of cherry-picked commits?

_Originally posted by @radeno in https://github.com/react-native-community/react-native-releases/issues/46#issuecomment-428494204_

**Comment by kelset** [comment]
So, couple things related to this:
>  there is no space where users and developers can read changelogs about patch versions of RN in friendly way.

well, that's not entirely true:

1. there are dedicated discussions about each minor on this repo precisely so that people can keep up to date with what is going on every version.
1. people can always go read the commit history in the dedicated release branch

That said

> Is there any way how to automatically generate changelog from release notes of cherry-picked commits?

No, at the moment there is no automatic way to generate the changelog, and the effort to work on it (as I've pointed out on this discussion about the [OSS RN cycle](https://github.com/react-native-community/discussions-and-proposals/issues/17)) is non trivial.

The reason that this Changelog.md file has not been updated with the "minor" versions changelog is simply because the person that had offered to help mostly with the changelog is currently not available.

I share your concern about the changelog not being as up-to-date as the code, and a couple days back I was literally talking about it with the Core - but I didn't have time yet to submit a PR with a new section per each of the two minors we have released for 0.57.

...but here's the catch - this is an OPEN SOURCE repo 🎉 you can always submit PRs to the .md file to update it, and I'd love for someone to help with it (and the main reason why I try to list both the commit message and the link to it when I post them in the issues).

**Comment by radeno** [comment]
> So, couple things related to this:
> 
> > there is no space where users and developers can read changelogs about patch versions of RN in friendly way.
> 
> well, that's not entirely true:
> 
> 1. there are dedicated discussions about each minor on this repo precisely so that people can keep up to date with what is going on every version.
> 2. people can always go read the commit history in the dedicated release branch
> 
You are right about it. But two weeks before i don't even know about react-native-releases and discussions-and-proposals repositories. For uninterested people on detailed development of RN it is invisible.
> That said
> 
> > Is there any way how to automatically generate changelog from release notes of cherry-picked commits?
> 
> No, at the moment there is no automatic way to generate the changelog, and the effort to work on it (as I've pointed out on this discussion about the [OSS RN cycle](https://github.com/react-native-community/discussions-and-proposals/issues/17)) is non trivial.

I see that React Native have different workflow about merging commits. In react they are merged naturally (purple icon about merging) it is "natural" way of Github. It looks like React Native do it in different way. Pull request is copied as commit and then original PR is closed (red icon).
Then there is hard way how to track changes. Because association between commit and PR is lost.
Use tools like https://github.com/github-tools/github-release-notes and https://github.com/github-tools/grunt-github-release-notes is then impossible. 
I made this PR decription https://github.com/facebook/react-native/pull/21561 but commit notes is so shrinked https://github.com/facebook/react-native/commit/4b6f02ea758a9ab5853a29ebfc054eaa98e6dc53 Part about changes for changelog missing.

With automated tools we could extract release changes from PR. Until when RN merging process will always closing PR instead merge it is hard to make any automated tool.

> 
> The reason that this Changelog.md file has not been updated with the "minor" versions changelog is simply because the person that had offered to help mostly with the changelog is currently not available.
> 
> I share your concern about the changelog not being as up-to-date as the code, and a couple days back I was literally talking about it with the Core - but I didn't have time yet to submit a PR with a new section per each of the two minors we have released for 0.57.
> 
> ...but here's the catch - this is an OPEN SOURCE repo 🎉 you can always submit PRs to the .md file to update it, and I'd love for someone to help with it (and the main reason why I try to list both the commit message and the link to it when I post them in the issues).

I think appending Changelog.md for patch versions could be made manually yet. To show "best" changes and at the end put link to see all diffs between current and last patch version.

**Comment by byCedric** [comment]
I also want to throw in tools like [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog). They are using Git instead of GitHub to create the changelog. Maybe there is some practical approach with the workflow of React Native?

**Comment by turnrye** [comment]
> Every minor (major because before version 1?) version of RN has nice description about what has changed but patch versions doesn't. I think there is legitimate requirement to tell what is different in every version. Many changes are significant (eg. Android studio 3.2/Xcode 10 support, some important fixes).

The changelog attempts to follow the [Keep a Changelog 1.0.0](https://keepachangelog.com/en/1.0.0/) format. All releases _should_ be entered, including patch releases. I've not been able to help as much recently, but I do plan to hop back in and help with this soon. There are some gaps in the document as well as the process that creates it.

> It could increase awareness about RN and making better apps because upgrading between last patch version and new minor version is less annoying (baby steps, less painful changes in code).

Completely agree! Going through this pain with a project this week.

> On the other hand it could also decrease opening some unnecessary issues on RN Github project cause every change is visible in human readable form.

+1

> Is there any way how to automatically generate changelog from release notes of cherry-picked commits?

This is something that I'm constantly weighing. The changelog entry today starts by reviewing the merge commits and trying to classify them based off of keywords. From there, related merges are combined, and the themes emerge. Due to the shared nature of the project (both internal FB development and community development), there is no kanban or WBS that we can look to to inform the changelog; the commits and then follow up discussion really are it. There are some special cases like reverse merges and commits straight to master/release branch that need handling, too.

A few things top-of-mind for me to do:

- Better document the process, especially around tool usage
- Ensure coverage for the existing patch releases
- Discuss incorporating changelog publishing to the release process to prevent future gaps

**Comment by TheSavior** [comment]
@turnrye How valuable are the release notes that are part of PRs? It seems like there is still a bunch of manual work necessary after that. 

What can we do to make that process easier in an automated way? I think we could consider revisiting enforcing something on the Facebook side if it would radically change the ability to create and maintain high quality changelogs.

**Comment by turnrye** [comment]
@TheSavior They are incredibly helpful, but I don't know that reviewers always check for completion or accuracy. I'd like to suggest some changes to the template, though.

As for the work that syncs from FB internal, the messages on the merge commits can be inconsistent. Some are [short and to the point](https://github.com/facebook/react-native/commit/ebf5aea) while others are [detailed with background and context](https://github.com/facebook/react-native/commit/1b09bd7). Then there are some that lack much detail at all; this is especially the case in bugfixes for recent changes (I don't have a good recent example). I think part of the breakdown here is that often times, there is information in internal FB systems referenced (like a D***).

I'd look for similar information in both sets of merge commits. I'm finishing collecting thoughts around this now, and I expect to share tomorrow afternoon.

**Comment by turnrye** [comment]
I'm going to start by:

- Updating the PR template to better match the changelog structure
- Tailing the accepted PRs and commenting on them to confirm descriptions and relationships with other recent PRs

I'll take this PR dialog approach for a while (maybe two releases) and then assess if a process should be established and where a tool can help.

If you have a suggestion of how I can engage internal users on synced merge commits, I'd greatly appreciate it.

**Comment by radeno** [comment]
@turnrye love your changes in template https://github.com/facebook/react-native/commit/ce18036c350cf562d480f856487852dc5a7f643d
As i made PR for version changelog https://github.com/react-native-community/react-native-releases/pull/72 i realized that we are missing type for changes that should be important for development but is not important for end-users.

@TheSavior reviewed https://github.com/react-native-community/react-native-releases/pull/69 and there are many changes which are not interesting for end-user developers. For them, no fix, no change or no new feature is added in public API. They use same code as before. It is for internal usage, as adding comments, better type checking, renaming private functions, typo fixing, code style changes etc.
Removing redundancies and lot of changes what they are no needed to read we can reduce "fear" to upgrade.

Something like removed `INTERNAL` category type? Maybe third pool like old `LOCATION`. Don't want to increase complexity. But still wan't to fill changelog rather than skip it completely.

**Comment by pvinis** [comment]
It is not the "friendliest" way, but I always check the diffs like https://github.com/facebook/react-native/compare/v0.58.2...v0.58.3

(Shameless plug: I add links for each upgrade [here](https://github.com/pvinis/rn-diff-purge))

**Comment by kelset** [comment]
hey folks, I think that a lot has changed since this issue has been opened so I'll proceed with closing :) we have now in place quite a few tools like the generator script to handle it 👍
